# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Insta Border' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Insta Border

  target 'Insta BorderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Insta BorderUITests' do
    # Pods for testing
  end

end
